{
 "title": "api",
 "time": { "from": "2026-03-12T14:13:12.116Z", "to": "2026-03-12T14:28:12.116Z" },
 "panels": [
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  1 -\n  (\n    (sum(rate(http_server_requests_seconds_count{job=\"api\", outcome=\"SERVER_ERROR\"}[5m])) or vector(0))\n    /\n    clamp_min(sum(rate(http_server_requests_seconds_count{job=\"api\"}[5m])), 1)\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_server_requests_seconds_bucket{job=\"api\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(\n  (sum(rate(http_server_requests_seconds_count{job=\"api\", outcome=\"SERVER_ERROR\"}[5m])) or vector(0))\n  /\n  clamp_min(sum(rate(http_server_requests_seconds_count{job=\"api\"}[5m])), 1)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"api\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"api\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}